# Generated by Django 4.2.5 on 2023-10-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dangun_app', '0002_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
