# Generated by Django 4.2.5 on 2023-09-21 06:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('product_id', models.IntegerField()),
                ('chatting', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('user_id', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('product_description', models.TextField()),
                ('deal_location', models.CharField(max_length=100)),
                ('product_img', models.ImageField(upload_to='product_img/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('views', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
